version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50M"
    max-file: "5"

services:
  web:
    container_name: story-maker-client-v3
    build:
      context: .
      dockerfile: ./DockerfileDev
    command: >
      sh -c "yarn install && yarn run dev"
    working_dir: /app
    volumes:
      - ./:/app/
    env_file:
      - .env
    logging: *default-logging
    ports:
      - 5173:5173
